--Kart sahiplerinin kaç kartı vardır?
SELECT name,COUNT(card) AS CARD_SAYISI FROM card_holder CH
JOIN credit_card CC ON CC.id_card_holder=CH.id
GROUP BY name 
ORDER BY CARD_SAYISI


--Hangi türde kaç işletme vardır?
SELECT MC.name,COUNT(M.name)AS ISLETME_SAYISI 
FROM MERCHANT M 
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
GROUP BY MC.name
ORDER BY ISLETME_SAYISI DESC


--Toplam işlem sayısı
SELECT COUNT(*)FROM TRANSACTIONS


--Kişi başı toplam harcama 
SELECT name,ROUND(SUM(amount),2) AS TOPLAM_HARCAMA 
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
GROUP BY name
ORDER BY 2 DESC


--Ocak ayı boyunca kişilerin hangi kartla hangi işletmeden ne zaman kaç dolarlık işlem yaptıkları sorgusu
SELECT CH.name AS KISI,
T.card,
M.name AS ISLETME,
T.amount AS HARCAMA,
T.date AS ZAMAN 
FROM TRANSACTIONS T
JOIN MERCHANT M ON T.id_merchant=M.id
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
WHERE DATE BETWEEN '2018-01-01 00:00:00' AND '2018-01-31 23:59:59'
ORDER BY ZAMAN,KISI,ISLETME


--ID numarası 25 olan kişinin ocak haziran arası günlük yaptığı işlemler sorgusu
SELECT T.date,T.amount,T.card,M.name,MC.name FROM TRANSACTIONS T 
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
JOIN MERCHANT M ON T.id_merchant=M.id
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
WHERE DATE BETWEEN '2018-01-01 00:00:00' AND '2018-05-31 23:59:59' 
AND CH.id=25
ORDER BY amount DESC


--ID numarası 2 olan kullanıcının 2.00$ altındaki harcama sayısı nedir?
SELECT AMOUNT FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
WHERE CH.id=2 AND T.amount<2.0


--ID numarası 18 olan kullanıcının 2.00$ altındaki harcama sayısı nedir?
SELECT AMOUNT FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
WHERE CH.id=18 AND T.amount<2.0


--Bütün Harcamaların yüzde kaçını hangi kullanıcı yapmıştır?
SELECT CH.id,COUNT(*) AS COUNT_,
ROUND(CONVERT(FLOAT,COUNT(*))/(SELECT COUNT(*) FROM TRANSACTIONS)*100,2)
AS PERCENT_
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
GROUP BY CH.id
ORDER BY COUNT_ DESC


--Kişi başı ortalama,maksimum,minimum harcamaları ve işlem sayıları nedir?
SELECT CH.NAME,
ROUND(AVG(amount),2) AS ORTALAMA_HARCAMA,
COUNT(amount) AS HARCAMA_SAYISI,
MAX(amount) AS MAKSIMUM_HARCAMA,
MIN(amount) AS MINIMUM_HARCAMA
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
GROUP BY CH.NAME
ORDER BY 2 DESC


--2.00$ altında en çok işlem yapan 5 kişi kimlerdir?
SELECT TOP 5 COUNT(*) AS ISLEM_SAYISI,
CH.id
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
WHERE T.amount<2.0  
GROUP BY CH.id
ORDER BY 1 DESC


--ID numarası 25 olan kişinin aylara ayrılmış olarak o aya ait harcama sayıları ve harcama yaptığı işletmenin türü nedir? (CASE WHEN)
--2.00$'dan az olan harcamalar şüphelidir. Minimum harcamaları 2.00$'dan küçük olanlar incelenmeli   
SELECT
T.amount,
COUNT(*) AS HARCAMANIN_ADEDI,
MC.name AS ISLETME_TURU,
CASE WHEN DATE BETWEEN '2018-01-01 00:00:00' AND '2018-01-31 23:59:59' THEN 'OCAK'
	   WHEN DATE BETWEEN '2018-02-01 00:00:00' AND '2018-02-28 23:59:59' THEN 'SUBAT'
	   WHEN DATE BETWEEN '2018-03-01 00:00:00' AND '2018-03-31 23:59:59' THEN 'MART'
	   WHEN DATE BETWEEN '2018-04-01 00:00:00' AND '2018-04-30 23:59:59' THEN 'NISAN'
	   WHEN DATE BETWEEN '2018-05-01 00:00:00' AND '2018-05-31 23:59:59' THEN 'MAYIS'
	   WHEN DATE BETWEEN '2018-06-01 00:00:00' AND '2018-06-30 23:59:59' THEN 'HAZIRAN'
	   WHEN DATE BETWEEN '2018-07-01 00:00:00' AND '2018-07-31 23:59:59' THEN 'TEMMUZ'
	   WHEN DATE BETWEEN '2018-08-01 00:00:00' AND '2018-08-31 23:59:59' THEN 'AGUSTOS'
	   WHEN DATE BETWEEN '2018-09-01 00:00:00' AND '2018-09-30 23:59:59' THEN 'EYLUL'
	   WHEN DATE BETWEEN '2018-10-01 00:00:00' AND '2018-10-31 23:59:59' THEN 'EKIM'
	   WHEN DATE BETWEEN '2018-11-01 00:00:00' AND '2018-11-30 23:59:59' THEN 'KASIM'
	   WHEN DATE BETWEEN '2018-12-01 00:00:00' AND '2018-12-31 23:59:59' THEN 'ARALIK'
	END AS AY
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
JOIN MERCHANT M ON T.id_merchant=M.id
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
WHERE CH.id=25 
GROUP BY T.amount,MC.name,T.date
HAVING AMOUNT<2.00 
ORDER BY 1


--Yukarıdaki sorunun aynısı ama maksimum,minimum ve ortalama değerleri de istenmekte birleştirme olarak da UNION ALL kullanıldı.
SELECT MONTH('20180101') AS AY,
MAX(AMOUNT) AS MAKSIMUM_HARCAMA,
MIN(AMOUNT) AS MINIMUM_HARCAMA,
ROUND(AVG(AMOUNT),2) AS ORTALAMA_HARCAMA,
COUNT(*) AS HARCAMA_SAYISI,
MC.name AS ISLETME_TURU
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
JOIN MERCHANT M ON T.id_merchant=M.id
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
WHERE DATE BETWEEN '2018-01-01 00:00:00' AND '2018-01-31 23:59:59' AND CH.id=25
GROUP BY MC.name
HAVING MIN(AMOUNT)<2.00 

UNION ALL 

SELECT MONTH('20180201') AS AY,
MAX(AMOUNT) AS MAKSIMUM_HARCAMA,
MIN(AMOUNT) AS MINIMUM_HARCAMA,
ROUND(AVG(AMOUNT),2) AS ORTALAMA_HARCAMA,
COUNT(*) AS HARCAMA_SAYISI,
MC.name AS ISLETME_TURU
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
JOIN MERCHANT M ON T.id_merchant=M.id
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
WHERE DATE BETWEEN '2018-02-01 00:00:00' AND '2018-02-28 23:59:59' AND CH.id=25
GROUP BY MC.name
HAVING MIN(AMOUNT)<2.00 

UNION ALL 

SELECT MONTH('20180301') AS AY,
MAX(AMOUNT) AS MAKSIMUM_HARCAMA,
MIN(AMOUNT) AS MINIMUM_HARCAMA,
ROUND(AVG(AMOUNT),2) AS ORTALAMA_HARCAMA,
COUNT(*) AS HARCAMA_SAYISI,
MC.name AS ISLETME_TURU
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
JOIN MERCHANT M ON T.id_merchant=M.id
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
WHERE DATE BETWEEN '2018-03-01 00:00:00' AND '2018-03-31 23:59:59' AND CH.id=25
GROUP BY MC.name
HAVING MIN(AMOUNT)<2.00 

UNION ALL 

SELECT MONTH('20180401') AS AY,
MAX(AMOUNT) AS MAKSIMUM_HARCAMA,
MIN(AMOUNT) AS MINIMUM_HARCAMA,
ROUND(AVG(AMOUNT),2) AS ORTALAMA_HARCAMA,
COUNT(*) AS HARCAMA_SAYISI,
MC.name AS ISLETME_TURU
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
JOIN MERCHANT M ON T.id_merchant=M.id
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
WHERE DATE BETWEEN '2018-04-01 00:00:00' AND '2018-04-30 23:59:59' AND CH.id=25
GROUP BY MC.name
HAVING MIN(AMOUNT)<2.00 

UNION ALL 

SELECT MONTH('20180501') AS AY,
MAX(AMOUNT) AS MAKSIMUM_HARCAMA,
MIN(AMOUNT) AS MINIMUM_HARCAMA,
ROUND(AVG(AMOUNT),2) AS ORTALAMA_HARCAMA,
COUNT(*) AS HARCAMA_SAYISI,
MC.name AS ISLETME_TURU
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
JOIN MERCHANT M ON T.id_merchant=M.id
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
WHERE DATE BETWEEN '2018-05-01 00:00:00' AND '2018-05-31 23:59:59' AND CH.id=25
GROUP BY MC.name
HAVING MIN(AMOUNT)<2.00 

UNION ALL 

SELECT MONTH('20180601') AS AY,
MAX(AMOUNT) AS MAKSIMUM_HARCAMA,
MIN(AMOUNT) AS MINIMUM_HARCAMA,
ROUND(AVG(AMOUNT),2) AS ORTALAMA_HARCAMA,
COUNT(*) AS HARCAMA_SAYISI,
MC.name AS ISLETME_TURU
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
JOIN MERCHANT M ON T.id_merchant=M.id
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
WHERE DATE BETWEEN '2018-06-01 00:00:00' AND '2018-06-30 23:59:59' AND CH.id=25
GROUP BY MC.name
HAVING MIN(AMOUNT)<2.00 

UNION ALL 

SELECT MONTH('20180701') AS AY,
MAX(AMOUNT) AS MAKSIMUM_HARCAMA,
MIN(AMOUNT) AS MINIMUM_HARCAMA,
ROUND(AVG(AMOUNT),2) AS ORTALAMA_HARCAMA,
COUNT(*) AS HARCAMA_SAYISI,
MC.name AS ISLETME_TURU
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
JOIN MERCHANT M ON T.id_merchant=M.id
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
WHERE DATE BETWEEN '2018-07-01 00:00:00' AND '2018-07-31 23:59:59' AND CH.id=25
GROUP BY MC.name
HAVING MIN(AMOUNT)<2.00 

UNION ALL 

SELECT MONTH('20180801') AS AY,
MAX(AMOUNT) AS MAKSIMUM_HARCAMA,
MIN(AMOUNT) AS MINIMUM_HARCAMA,
ROUND(AVG(AMOUNT),2) AS ORTALAMA_HARCAMA,
COUNT(*) AS HARCAMA_SAYISI,
MC.name AS ISLETME_TURU
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
JOIN MERCHANT M ON T.id_merchant=M.id
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
WHERE DATE BETWEEN '2018-08-01 00:00:00' AND '2018-08-31 23:59:59' AND CH.id=25
GROUP BY MC.name
HAVING MIN(AMOUNT)<2.00 

UNION ALL 

SELECT MONTH('20180901') AS AY,
MAX(AMOUNT) AS MAKSIMUM_HARCAMA,
MIN(AMOUNT) AS MINIMUM_HARCAMA,
ROUND(AVG(AMOUNT),2) AS ORTALAMA_HARCAMA,
COUNT(*) AS HARCAMA_SAYISI,
MC.name AS ISLETME_TURU
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
JOIN MERCHANT M ON T.id_merchant=M.id
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
WHERE DATE BETWEEN '2018-09-01 00:00:00' AND '2018-09-30 23:59:59' AND CH.id=25
GROUP BY MC.name
HAVING MIN(AMOUNT)<2.00 

UNION ALL 

SELECT MONTH('20181001') AS AY,
MAX(AMOUNT) AS MAKSIMUM_HARCAMA,
MIN(AMOUNT) AS MINIMUM_HARCAMA,
ROUND(AVG(AMOUNT),2) AS ORTALAMA_HARCAMA,
COUNT(*) AS HARCAMA_SAYISI,
MC.name AS ISLETME_TURU
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
JOIN MERCHANT M ON T.id_merchant=M.id
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
WHERE DATE BETWEEN '2018-10-01 00:00:00' AND '2018-10-31 23:59:59' AND CH.id=25
GROUP BY MC.name
HAVING MIN(AMOUNT)<2.00 

UNION ALL 

SELECT MONTH('20181101') AS AY,
MAX(AMOUNT) AS MAKSIMUM_HARCAMA,
MIN(AMOUNT) AS MINIMUM_HARCAMA,
ROUND(AVG(AMOUNT),2) AS ORTALAMA_HARCAMA,
COUNT(*) AS HARCAMA_SAYISI,
MC.name AS ISLETME_TURU
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
JOIN MERCHANT M ON T.id_merchant=M.id
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
WHERE DATE BETWEEN '2018-11-01 00:00:00' AND '2018-11-30 23:59:59' AND CH.id=25
GROUP BY MC.name
HAVING MIN(AMOUNT)<2.00 

UNION ALL 

SELECT MONTH('20181201') AS AY,
MAX(AMOUNT) AS MAKSIMUM_HARCAMA,
MIN(AMOUNT) AS MINIMUM_HARCAMA,
ROUND(AVG(AMOUNT),2) AS ORTALAMA_HARCAMA,
COUNT(*) AS HARCAMA_SAYISI,
MC.name AS ISLETME_TURU
FROM TRANSACTIONS T
JOIN CREDIT_CARD CC ON T.card=CC.card
JOIN CARD_HOLDER CH ON CC.id_card_holder=CH.id
JOIN MERCHANT M ON T.id_merchant=M.id
JOIN MERCHANT_CATEGORY MC ON M.id_merchant_category=MC.id
WHERE DATE BETWEEN '2018-12-01 00:00:00' AND '2018-12-31 23:59:59' AND CH.id=25 
GROUP BY MC.name
HAVING MIN(AMOUNT)<2.00 




